# Usa una imagen base de Node.js
FROM node:18

# Usa una imagen base de Node.js
FROM node:18

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias incluyendo nodemon
RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Expone el puerto 3000 para acceder a la API
EXPOSE 3000

# Comando para ejecutar la aplicación en modo desarrollo con nodemon
CMD ["npm", "run", "dev"]
